version: "3.9"
services:
  backend:
    build:
      context: . 
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8000"  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"